### PR TITLE
Modify a little for Query class

### PR DESCRIPTION
**Pull request by wrocla**
This pull request modifies a little for Query class.
 - Remove unused alias(:to_a :collection) in Query class
 - Modify initial setting of tracking_scope for Query Model

### CODE REVIEW

**Comment by tpitale** [comment]
The alias of `to_a` and `collection` is for user code. Please do not remove that.

**Comment by wrocla** [comment]
@tpitale 
Thank you for pointing it out.
I revert the alias to the original.

**Comment by tpitale** [comment]
So, this change allows you to pass `tracking_scope` as an option when calling `results`. Can you tell me a little more about how you'd like to use this?

**Comment by wrocla** [comment]
I know that it can set tracking_scope(ex 'mcf') to instance(Query class) of calling `results` output.
But, I want to set tracking_scope when `results` method is called.

```
Exit.results(profile, start_date: start_date, end_date: end_date, tracking_scope: 'mcf')
```

**Pull request merged**
