### PR TITLE
Add quota user and user ip to User

### LINKED ISSUE #105: Adding quotaUser parameter to management API calls ?
Hi and first of all thanks for this gem! We're using it in a Rails app to display statistics to our users. We've been running into the quota exceeded errors, so we've added the quotaUser setting to the results calls as documented. However, due to the way we load the data (ajax call to our server -> Legato to GA), we need to set up the profile/account for each request and these calls also run into the quota limit.

I found no way to add the quotaUser parameter to the management API calls so I cobbled this together:

```
Legato::User.class_eval do
  attr_accessor :quota_user
end
Legato::Management::Finder.class_eval do
  alias_method :original_uri_for_user, :uri_for_user
  def uri_for_user(user, path)
    original = original_uri_for_user(user, path)
    uri = if user.quota_user
      p = "quotaUser=#{user.quota_user}"
      if original =~ /\?/
        original + "&#{p}"
      else
        original + "?#{p}"
      end
    else
      original
    end
#    puts "original: " + original
#    puts "overridden: " + uri
    uri
  end
end
```

I'd like to submit a pull request, however I'd love to have some guidance where the best place to put the accessor etc. would be...

### PR DESCRIPTION
**Pull request by tpitale**
* Add quota_user attribute to `User`
* Add user_ip attribute to `User`
* Set quota user and user ip on `Legato::Query`
* Add quotaUser and userIp to params from `Legato::Management::Query` and `Legato::Query`

Resolves #105

### CODE REVIEW

**Comment by tpitale** [comment]
@MGPalmer mind trying this out?

**Comment by MGPalmer** [comment]
That seems to be working perfectly for me :)

Will you be releasing a new version for this ?

**Comment by tpitale** [comment]
I'll release a version shortly.

**Comment by MGPalmer** [comment]
\o/

**Comment by tpitale** [comment]
Released 0.5.2

**Comment by MGPalmer** [comment]
Thanks a bunch, I'll upgrade and re-test on monday :)

**Comment by MGPalmer** [comment]
Yep, still works - thanks a lot for the fast turnaround !

**Comment by tpitale** [comment]
Great! Thanks for testing.

**Pull request merged**
